
find_path(GEPARD_LIBRARY_DIR "libgepard.so"
    PATHS GEPARD_INSTALL_DIR "${GEPARD_INSTALL_DIR}/lib")
            
find_path(GEPARD_INCLUDE_DIR "gepard.h"
    PATHS GEPARD_INSTALL_DIR "${GEPARD_INSTALL_DIR}/include")

set(GEPARD_LIBS "${GEPARD_LIBRARY_DIR}/libgepard.so")

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Gepard REQUIRED_VARS GEPARD_LIBRARY_DIR GEPARD_INCLUDE_DIR GEPARD_LIBS)
